# Generated by Django 5.2.7 on 2025-11-05 22:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_celery_results", "0014_alter_taskresult_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^r", message="Must start with 'r'"
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("language", models.CharField(max_length=2)),
                ("markets", models.JSONField()),
                ("status", models.CharField(max_length=10)),
                ("publication_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(default="https://cookidoo.thermomix.com/")),
                ("locale", models.CharField(max_length=5)),
                ("headers", models.JSONField(blank=True, default=dict, null=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ScrapedRecipe",
            fields=[
                (
                    "scrape_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                ("success", models.BooleanField()),
                ("raw_data", models.JSONField(default=dict)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "celery_task",
                    models.ForeignKey(
                        editable=False,
                        help_text="Celery task associated with this scrape",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_results.taskresult",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cookidoo.recipe",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cookidoo.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-scraped_at"],
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="source",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cookidoo.source",
            ),
        ),
    ]
