# Generated by Django 5.2.17 on 2026-09-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookidoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='scrape_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='scrape_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=15),
        ),
    ]
