# Generated by Django 5.2.17 on 2026-09-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookidoo', '0002_recipe_last_scraped_at_recipe_scrape_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedrecipe',
            name='content_hash',
            field=models.CharField(blank=True, editable=False, help_text='SHA-256 of raw_data, used to detect no-op rescrapes', max_length=64, null=True),
        ),
    ]
