# Generated by Django 5.2.17 on 2026-09-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookidoo", "0004_seed_nightly_rescrape_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="is_default",
        ),
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.URLField(),
        ),
    ]
