"""
Django settings for cookistash project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-98^@bq!rg^wqq)iei8+27=sw+r1u+uzd)mfjj(t&mwykp2c$-t")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [h for h in os.environ.get("ALLOWED_HOSTS", "*").split(",") if h]

# Needed behind any reverse proxy that doesn't forward the exact original
# Host header (port included) - CSRF's Origin check compares the browser's
# Origin against http(s)://<request Host>, so a mismatch here 403s every
# POST. Empty by default; set to e.g. "https://cookistash.example.com".
CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o]


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_json_widget",
    "django_celery_results",
    "django_celery_beat",
    "cookistash.cookidoo",
    "cookistash.mealie",
]

UNFOLD = {
    "SITE_TITLE": "Cookistash",
    "SITE_HEADER": "Cookistash Admin",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "cookistash.middleware.AutoAdminLoginMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Auto-authenticate every request as the superuser, skipping the admin login
# form. Only safe when this host isn't reachable by anyone but you - set
# AUTO_ADMIN_LOGIN=false (env var) if this ever gets exposed beyond localhost.
AUTO_ADMIN_LOGIN = os.environ.get("AUTO_ADMIN_LOGIN", "true").lower() == "true"

ROOT_URLCONF = "cookistash.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cookistash.context_processors.app_version",
            ],
        },
    },
]

WSGI_APPLICATION = "cookistash.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "cookistash"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "postgres"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True
DATETIME_FORMAT = "N j"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
# Only used by `collectstatic` for the gunicorn/nginx path (docker-compose) -
# `manage.py runserver` (local dev) serves straight from each app's static/
# dir via django.contrib.staticfiles and never touches this.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery configs
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "django-db")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
# Off by default - without it, TaskResult rows never get task_name/args/
# kwargs/worker populated, only status/result, making the admin useless for
# figuring out which recipe a task result belongs to.
CELERY_RESULT_EXTENDED = True

# Periodic tasks are managed via django-celery-beat (DB-backed schedules,
# editable at /admin/django_celery_beat/periodictask/) instead of the static
# CELERY_BEAT_SCHEDULE dict - the standard approach when schedules need to be
# inspectable/editable without a redeploy. The default nightly rescrape job
# is auto-seeded by a data migration (see cookidoo/migrations).
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
