# Generated by Django 5.2.7 on 2025-11-05 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cookidoo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "plural_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("label_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("api_url", models.URLField()),
                ("api_token", models.CharField(max_length=350)),
                ("headers", models.JSONField(blank=True, default=dict, null=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("plural_name", models.CharField(max_length=50)),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "plural_abbreviation",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("use_abbreviation", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "reference_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("display", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("original_text", models.TextField(blank=True, null=True)),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="mealie.food",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="mealie.unit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.UUIDField(editable=False, unique=True)),
                (
                    "slug",
                    models.SlugField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "rating",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("org_url", models.URLField()),
                (
                    "recipe_servings",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "recipe_yield_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "recipe_yield",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_time", models.CharField(blank=True, max_length=255, null=True)),
                ("prep_time", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "perform_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("tools", models.JSONField(blank=True, default=list)),
                ("recipe_instructions", models.JSONField(blank=True, default=list)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("notes", models.JSONField(blank=True, default=list)),
                (
                    "recipe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cookidoo.recipe",
                    ),
                ),
                (
                    "recipe_ingredients",
                    models.ManyToManyField(
                        blank=True, null=True, to="mealie.ingredient"
                    ),
                ),
                (
                    "scraped_recipe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraped_recipe",
                        to="cookidoo.scrapedrecipe",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
