# Generated by Django 5.2.7 on 2025-11-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mealie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="id",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
