# Generated by Django 5.2.7 on 2025-11-05 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mealie", "0002_alter_recipe_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="recipe_ingredients",
            new_name="recipe_ingredient",
        ),
    ]
