# Generated by Django 5.2.7 on 2025-11-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mealie", "0003_rename_recipe_ingredients_recipe_recipe_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="plural_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
