# Generated by Django 5.2.7 on 2025-11-09 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mealie", "0004_alter_unit_plural_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True)),
                ("summary", models.CharField(max_length=50, null=True)),
                ("formatted_text", models.TextField()),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mealie.recipe"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
