# Generated by Django 5.2.17 on 2026-09-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealie', '0005_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='synced_hash',
            field=models.CharField(blank=True, editable=False, help_text='content_hash of the ScrapedRecipe last successfully pushed to Mealie', max_length=64, null=True),
        ),
    ]
