# Generated by Django 5.2.17 on 2026-09-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealie', '0006_recipe_last_synced_at_recipe_synced_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='group_slug',
            field=models.CharField(default='home', help_text="Mealie group slug used to build recipe links, e.g. 'home'.", max_length=100),
        ),
        migrations.AddField(
            model_name='source',
            name='public_url',
            field=models.URLField(blank=True, help_text='Browser-facing URL, e.g. http://localhost:9000. Falls back to api_url if blank.', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='api_url',
            field=models.URLField(help_text='Server-to-server API URL, e.g. http://mealie:9000 on the docker network.'),
        ),
    ]
