# Generated by Django 5.2.17 on 2026-09-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealie', '0007_source_group_slug_source_public_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='extras',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_category',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
