# Generated by Django 5.2.17 on 2026-09-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealie', '0008_recipe_extras_recipe_nutrition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mealie_slug',
            field=models.SlugField(blank=True, editable=False, help_text="Mealie's own slug for this recipe (it always re-derives this from the display name on write, so it can't be pinned to our slug/id).", null=True),
        ),
    ]
