# Generated by Django 5.2.17 on 2026-09-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealie', '0009_recipe_mealie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='settings',
        ),
    ]
