# Generated by Django 5.2.17 on 2026-09-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealie', '0010_remove_recipe_recipe_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cookidoo_ref',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='cookidoo_ref',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
