# Generated by Django 5.2.17 on 2026-09-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealie', '0011_food_cookidoo_ref_unit_cookidoo_ref_alter_food_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='mealie_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='mealie_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
