# Generated by Django 5.2.17 on 2026-09-22 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mealie", "0012_food_mealie_id_unit_mealie_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="is_default",
        ),
    ]
